In [2]:
!pip install mobilechelonian

In [4]:
from mobilechelonian import Turtle

In [8]:
t=Turtle()
t.speed(5)
colours=["red","blue","yellow","brown","black","purple","green"]

t.penup(); t.left(90); t.forward(200); t.right(90); t.pendown()
for i in range (0,18):
    t.pencolor(colours[i%7])
    t.right(20)
    t.forward(50)
    
t.right(180)
t.home()

Turtle()

In [46]:
t=Turtle()
t.speed(4)
colours=["red","blue","yellow","brown","black","purple","green"]


t.penup(); 
t.left(225); t.forward(70); t.right(135); 
t.pendown() 
t.pencolor(colours[4])
for i in range(4):
    t.forward(100);
    t.right(90);    

t.penup(); 
t.home();

Turtle()

In [53]:
#Diseñar un programa que sume dos tuplas de números

#--------------------------------------------Variables----------------------------------------------------------------#
#
a=[1,2,3,4,5,6]
b=[1,2,3,4,5,6]
c=[]
la=len(a)
lb=len(b)
i=0
#
#--------------------------------------------Código------------------------------------------------------------------#
if la==lb:
    while i<la:
              c.append(a[i]+b[i])
              i+=1
    print(c)
else:
    print("Tuplas de longitud diferete")
            
    

[2, 4, 6, 8, 10, 12]


In [60]:
#Diseñar un programa que multiplique un vector por una constate

#--------------------------------------------Variables----------------------------------------------------------------#
#
a=[1,2,3,4,5,6]
constante
c=[]
la=len(a)

i=0
#
#--------------------------------------------Código------------------------------------------------------------------#

while i<la:
          c.append(a[i]*constante)
          i+=1
print(c)

    

[10, 20, 30, 40, 50, 60]


In [58]:
#Diseñar un programa que sume dos vectores 

#--------------------------------------------Variables----------------------------------------------------------------#
#
i=0
n1=[]
n2=[]
c=0
r=[]
#
#--------------------------------------------Código------------------------------------------------------------------#
l=int(input("Tamaño de los vectores: "))
print("Valores del vector 1")
while i<l:    
    n1.append(int(input("Valor :")))
    #n1.append(int(input(print("Valor",i+1,":"))))
    i+=1      
i=0
print("Valores del vector 2")
while i<l:    
    n2.append(int(input("Valor :")))
    #n2.append(int(input(print("Valor",i+1,":"))))
    i+=1    
i=0
print("")
print("Vector 1:",n1)
print("Vector 2:",n2)
while i<l:  
    r.append(n1[i]+n2[i])
    i+=1
    
print("Su suma vectorial es:",r)
            
    

Tamaño de los vectores: 2
Valores del vector 1
Valor :1
Valor :1
Valores del vector 2
Valor :1
Valor :1

Vector 1: [1, 1]
Vector 2: [1, 1]
Su suma vectorial es: [2, 2]


In [55]:
#Diseñar un programa que pida los valores de dos vectores y realice el producto punto de estos

#--------------------------------------------Variables----------------------------------------------------------------#
#
i=0
n1=[]
n2=[]
c=0
r=0
#
#--------------------------------------------Código------------------------------------------------------------------#
l=int(input("Tamaño de los vectores: "))
print("Valores del vector 1")
while i<l:    
    n1.append(int(input("Valor :")))
    #n1.append(int(input(print("Valor",i+1,":"))))
    i+=1      
i=0
print("Valores del vector 2")
while i<l:    
    n2.append(int(input("Valor :")))
    #n2.append(int(input(print("Valor",i+1,":"))))
    i+=1    
i=0
print("")
print("Vector 1:",n1)
print("Vector 2:",n2)
while i<l:  
    r+=(n1[i]*n2[i])
    i+=1
print("Su producto punto es:",r)

Tamaño de los vectores: 2
Valores del vector 1
Valor :1
Valor :2
Valores del vector 2
Valor :3
Valor :4

Vector 1: [1, 2]
Vector 2: [3, 4]
Su producto punto es: 11


In [ ]:
#Diseñar un programa que realice la multiplicacion de dos matrices


#--------------------------------------------Variables----------------------------------------------------------------#


#--------------------------------------------Código------------------------------------------------------------------#







In [59]:
import numpy as np

In [63]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print (type(x))
print(x*y)


[5 7 9]
<class 'numpy.ndarray'>
[ 4 10 18]


In [64]:
x+y

array([5, 7, 9])

In [65]:
x-y

array([-3, -3, -3])

In [66]:
x*40000

array([ 40000,  80000, 120000])

In [67]:
y*10

array([40, 50, 60])

Productos punto

In [71]:
x=np.array([2,1,3])
y=np.array([4,6,7])

print(sum(x*y))

35


In [72]:
np.dot(x,y)

35

In [74]:
x.dot(y)

35

In [75]:
x@y

35

In [77]:
np.linalg.norm(x)

3.7416573867739413

In [79]:
np.sqrt(np.dot(x,x))

3.7416573867739413

Matrices
--

In [91]:
A = np.array([ [1, 3, 2],[1, 0, 0],[1, 2, 2] ])
print("A: ")
print(A)

B=np.array([[1, 0, 5],
       [7, 5, 0],
       [2, 1, 1]])
print("B: ")
print(B)

A: 
[[1 3 2]
 [1 0 0]
 [1 2 2]]
B: 
[[1 0 5]
 [7 5 0]
 [2 1 1]]


In [93]:
A+B

array([[2, 3, 7],
       [8, 5, 0],
       [3, 3, 3]])

In [94]:
A-B

array([[ 0,  3, -3],
       [-6, -5,  0],
       [-1,  1,  1]])

In [95]:
A*50

array([[ 50, 150, 100],
       [ 50,   0,   0],
       [ 50, 100, 100]])

In [96]:
A*B

array([[ 1,  0, 10],
       [ 7,  0,  0],
       [ 2,  2,  2]])

Multiplicacion de matrices

A*B es multiplicacion elemento a elemento

A@B es multiplicacion algebraica

In [97]:
A@B

array([[26, 17,  7],
       [ 1,  0,  5],
       [19, 12,  7]])

In [98]:
A.shape

(3, 3)

In [99]:
A.size

9

In [100]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.arange(1,10,.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [103]:
print(np.arange(1,13).reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [105]:
I=np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [106]:
I=np.eye(2,3)
I

array([[1., 0., 0.],
       [0., 1., 0.]])

In [108]:
A=np.array([ [4, 7],[2, 6]])
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [109]:
np.transpose(A)

array([[4, 2],
       [7, 6]])

In [110]:
A.T

array([[4, 2],
       [7, 6]])

In [111]:
np.linalg.det(A)

10.000000000000002

RESOLVER
--

x-2y=1

3x+2y=11

y=(1-x)/-2

In [138]:
A=np.array([[1, -2],
       [3, 2]])

B=np.array([[1],
       [11]])

inV=np.linalg.inv
X=inV(A)

print("A: ")
print(A)
print("B: ")
print(B)

print("Respuesta")
X=A_i@B
print(X)




A: 
[[ 1 -2]
 [ 3  2]]
B: 
[[ 1]
 [11]]
Respuesta
[[3.]
 [1.]]


In [131]:
print(A@R) #Comprobacion

[[ 1.]
 [11.]]


In [114]:
A[0]

array([ 1, -2])

In [115]:
A[:,0]

array([1, 3])

In [118]:
C=np.array([[5, -8],
       [5, 4]])
C

array([[ 5, -8],
       [ 5,  4]])

In [119]:
C[:,0]=A[:,0]
C

array([[ 1, -8],
       [ 3,  4]])

RESOLVER
--

 
 x + 2y + 3z = 6

2x + 5y + 2z = 4

6x - 3y +  z = 2

In [141]:
A1=np.array([[1, 2, 3],
       [2, 5, 2],[6,-3,1]])

B1=np.array([[6],
       [4],[2]])

inV=np.linalg.inv
A_i=inV(A1)

print("A: ")
print(A)
print("B: ")
print(B)

print("Respuesta")
X=A_i@B1
print(X)



A: 
[[ 1  2  3]
 [ 2  5  2]
 [ 6 -3  1]]
B: 
[[6]
 [4]
 [2]]
Respuesta
[[-1.11022302e-16]
 [-6.93889390e-17]
 [ 2.00000000e+00]]
